[package]
name = "amxmodx-utils"
version = "0.0.1"
authors = ["Fedcomp"]
edition = "2018"

[features]
# Treat warnings as a build error.
strict = []

[dependencies]
bytes = "0.4.12"
flate2 = { version = "1.0", features = ["rust_backend"], default-features = false }